import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', loadComponent: () => import('./pages/home/home').then(m => m.Home) },
  { path: 'installation', loadComponent: () => import('./pages/installation/installation').then(m => m.Installation) },
  { path: 'license', loadComponent: () => import('./pages/license/license').then(m => m.License) },
  { path: 'pk-accordion', loadComponent: () => import('./pages/pk-accordion/pk-accordion-page').then(m => m.PkAccordionPage) },
  { path: 'pk-calendar', loadComponent: () => import('./pages/pk-calendar/pk-calendar-page').then(m => m.PkCalendarPage) },
  { path: 'pk-timeline', loadComponent: () => import('./pages/pk-timeline/pk-timeline-page').then(m => m.PkTimelinePage) },
  { path: 'pk-tabs', loadComponent: () => import('./pages/pk-tabs/pk-tabs-page').then(m => m.PkTabsPage) },
  { path: 'pk-toastr', loadComponent: () => import('./pages/pk-toastr/pk-toastr-page').then(m => m.PkToastrPage) },
  { path: 'pk-alert', loadComponent: () => import('./pages/pk-alert/pk-alert-page').then(m => m.PkAlertPage) },
  { path: 'pk-modal', loadComponent: () => import('./pages/pk-modal/pk-modal-page').then(m => m.PkModalPage) },
  { path: 'pk-icon', loadComponent: () => import('./pages/pk-icon/pk-icon-page').then(m => m.PkIconPage) },
  { path: 'pk-datagrid', loadComponent: () => import('./pages/pk-datagrid/pk-datagrid-page').then(m => m.PkDatagridPage) },
  { path: 'pk-datepicker', loadComponent: () => import('./pages/pk-datepicker/pk-datepicker-page').then(m => m.PkDatepickerPage) },
  { path: 'pk-progress', loadComponent: () => import('./pages/pk-progress/pk-progress-page').then(m => m.PkProgressPage) },
  { path: 'pk-treeview', loadComponent: () => import('./pages/pk-treeview/pk-treeview-page').then(m => m.PkTreeviewPage) },
  { path: 'pk-select', loadComponent: () => import('./pages/pk-select/pk-select-page').then(m => m.PkSelectPage) },
  { path: 'pk-autocomplete', loadComponent: () => import('./pages/pk-autocomplete/pk-autocomplete-page').then(m => m.PkAutocompletePage) },
  { path: 'pk-typeahead', loadComponent: () => import('./pages/pk-typeahead/pk-typeahead-page').then(m => m.PkTypeaheadPage) },
  { path: 'pk-file-upload', loadComponent: () => import('./pages/pk-file-upload/pk-file-upload-page').then(m => m.PkFileUploadPage) },
  { path: 'pk-heatmap', loadComponent: () => import('./pages/pk-heatmap/pk-heatmap-page').then(m => m.PkHeatmapPage) },
  { path: 'pk-input-password', loadComponent: () => import('./pages/pk-input-password/pk-input-password-page').then(m => m.PkInputPasswordPage) },
  { path: 'pk-split', loadComponent: () => import('./pages/pk-split/pk-split-page').then(m => m.PkSplitPage) },
  { path: 'pk-textarea', loadComponent: () => import('./pages/pk-textarea/pk-textarea-page').then(m => m.PkTextareaPage) },
  { path: 'pk-sidenav', loadComponent: () => import('./pages/pk-sidenav/pk-sidenav').then(m => m.PkSidenavPage) },
  { path: 'pk-float-btn', loadComponent: () => import('./pages/pk-float-btn/pk-float-btn.component').then(m => m.PkFloatBtnComponent) },
  { path: 'pk-table', loadComponent: () => import('./pages/pk-table/pk-table-page').then(m => m.PkTablePage) },
  { path: 'pk-toggle', loadComponent: () => import('./pages/pk-toggle/pk-toggle-page').then(m => m.PkTogglePage) },
  { path: 'pk-font', loadComponent: () => import('./pages/pk-font/pk-font-page').then(m => m.PkFontPage) },
  { path: 'pk-grid', loadComponent: () => import('./pages/pk-grid/pk-grid-page').then(m => m.PkGridPage) },
  { path: 'pk-btn', loadComponent: () => import('./pages/pk-btn/pk-btn-page').then(m => m.PkBtnPage) },
  { path: 'pk-spinner', loadComponent: () => import('./pages/pk-spinner/pk-spinner-page').then(m => m.PkSpinnerPage) },
  { path: 'pk-badge', loadComponent: () => import('./pages/pk-badge/pk-badge-page').then(m => m.PkBadgePage) },
  { path: 'pk-card', loadComponent: () => import('./pages/pk-card/pk-card-page').then(m => m.PkCardPage) },
  { path: 'pk-breadcrumb', loadComponent: () => import('./pages/pk-breadcrumb/pk-breadcrumb-page').then(m => m.PkBreadcrumbPage) },
  { path: 'pk-divider', loadComponent: () => import('./pages/pk-divider/pk-divider-page').then(m => m.PkDividerPage) },
  { path: 'pk-tooltip', loadComponent: () => import('./pages/pk-tooltip/pk-tooltip-page').then(m => m.PkTooltipPage) },
  { path: 'pk-form', loadComponent: () => import('./pages/pk-form/pk-form-page').then(m => m.PkFormPage) },
  { path: 'pk-layout', loadComponent: () => import('./pages/pk-layout/pk-layout-page').then(m => m.PkLayoutPage) },
  { path: 'pk-markdown-viewer', loadComponent: () => import('./pages/pk-markdown-viewer/pk-markdown-viewer-page').then(m => m.PkMarkdownViewerPage) },
  { path: 'pk-barcode', loadComponent: () => import('./pages/pk-barcode/pk-barcode-page').then(m => m.PkBarcodePage) },
  { path: 'pk-qrcode', loadComponent: () => import('./pages/pk-qrcode/pk-qrcode-page').then(m => m.PkQrcodePage) },
  { path: 'pk-code-reader', loadComponent: () => import('./pages/pk-code-reader/pk-code-reader-page').then(m => m.PkCodeReaderPage) },
  { path: 'pk-radio-group', loadComponent: () => import('./pages/pk-radio-group/pk-radio-group-page').then(m => m.PkRadioGroupPage) },
  { path: 'pk-timepicker', loadComponent: () => import('./pages/pk-timepicker/pk-timepicker-page').then(m => m.PkTimepickerPage) },
  { path: 'pk-context-menu', loadComponent: () => import('./pages/pk-context-menu/pk-context-menu-page').then(m => m.PkContextMenuPage) },
  { path: 'pk-pipes', loadComponent: () => import('./pages/pk-pipes/pk-pipes-page').then(m => m.PkPipesPage) },
  { path: 'pk-directives', loadComponent: () => import('./pages/pk-directives/pk-directives-page').then(m => m.PkDirectivesPage) },
  { path: 'pk-otp', loadComponent: () => import('./pages/pk-otp/pk-otp-page').then(m => m.PkOtpPage) },
  { path: 'pk-export', loadComponent: () => import('./pages/pk-export/pk-export-page').then(m => m.PkExportPage) },
  // Examples
  { path: 'examples/login', loadComponent: () => import('./pages/examples/login/login-example').then(m => m.LoginExample) },
  { path: 'examples/chat', loadComponent: () => import('./pages/examples/chat/chat-example').then(m => m.ChatExample) },
  { path: 'examples/dashboard', loadComponent: () => import('./pages/examples/dashboard/dashboard-example').then(m => m.DashboardExample) },
  { path: 'examples/landing', loadComponent: () => import('./pages/examples/landing/landing-example').then(m => m.LandingExample) },
];
